HRM_System/Controllers/AdminsController.cs
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Constants;
using HRM_System.Constants;
using HRM_System.Data;
using HRM_System.Data.Base;
using HRM_System.Models;
using HRM_System.Models.ViewModel;
using HRM_System.seeds;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore; 

namespace HRM_System.Controllers
{
 //   [Authorize(Roles = Roles.HRAdmin)]
    public class AdminsController : Controller
    {
        private readonly IEntityRepository<Admin> _adminRepo;
        private readonly IEntityRepository<HRUser> _HRRepo;
        private readonly UserManager<HRUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IEntityRepository<Usergroupsandpermissions> _groupRepo;
        private readonly AppDbContext _context;

        public AdminsController(IEntityRepository<Admin> adminRepo,
            IEntityRepository<HRUser> HRRepo,
            UserManager<HRUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IEntityRepository<Usergroupsandpermissions> groupRepo, AppDbContext context)
        {
            _adminRepo = adminRepo;
            _HRRepo = HRRepo;
            _userManager = userManager;
            _roleManager = roleManager;
            _groupRepo = groupRepo;
            _context = context;
        }
        [Authorize(permissions.Admin.View)]
        public async Task<IActionResult> All()
        {
            var employee = (await _adminRepo.GetAllAsync()).Include(e => e.HRUser);

            return View(employee);
        }

        public IActionResult CreateAdmin()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdmin(HRviewModel Admin)
        {
            if (ModelState.IsValid)
            {
                var admin = new HRUser()
                {
                    FullName = Admin.FullName,
                    Email = Admin.Email,
                    UserName = Admin.Email.Split('@')[0],
                    Admin = new Admin
                    {
                        Email = Admin.Email,
                        UserName = Admin.UserName,
                        Password = Admin.Password,
                        RoleName=Admin.RoleName,
                    }
                };

                var result = await _userManager.CreateAsync(admin, Admin.Password);

                if (result.Succeeded)
                {
                    var role = await _userManager.AddToRoleAsync(admin, Admin.RoleName);

                    return View("All" , (await _adminRepo.GetAllAsync()).Include(e => e.HRUser));
                }


                foreach (var item in result.Errors)
                    ModelState.AddModelError(string.Empty, item.Description);
                return View(Admin);
            }

            return View(Admin);
        }



        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                var admin = (await _adminRepo.GetByIdAsync((int)id));

                if (admin != null)
                {
                    await _context.Entry(admin)
                        .Reference(e => e.HRUser)
                        .LoadAsync();

                    return View(admin);
                }
                else
                {
                    return NotFound();
                }
            }
            else
            {
                return NotFound();
            }
        }

        public async Task< IActionResult> Edit(int? id)
        {
            return await Details(id);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int? id, Admin Updateadmin)
        {
            if (id != Updateadmin.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var admin = (await _adminRepo.GetByIdAsync((int)id));
                var user = await _userManager.FindByEmailAsync(admin.Email);
                if(user != null)
                {
                    user.Email = Updateadmin.Email;
                    user.FullName = Updateadmin.HRUser.FullName;
                    user.UserName = Updateadmin.Email.Split('@')[0];
                }
                if(admin != null)
                {
                    admin.Email = Updateadmin.Email;
                    admin.UserName = Updateadmin.UserName;
                    admin.Password = Updateadmin.Password;
                    admin.RoleName = Updateadmin.RoleName;
                }
                await _userManager.UpdateAsync(user);
                var userRoles = await _userManager.GetRolesAsync(user);

                await _userManager.RemoveFromRolesAsync(user, userRoles);
                var result = await _userManager.AddToRoleAsync(user, Updateadmin.RoleName);
               
                await _adminRepo.UpdateAsync(admin);
                    return RedirectToAction(nameof(All));
                
            }
            return View(Updateadmin);
        }

        public Task<IActionResult> Delete(int? id)
        {
            return Details(id);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? id, Admin admin)
        {
            if (admin.Id != id)
                return BadRequest();
            var Admin = (await _adminRepo.GetByIdAsync((int)id));
            var user = await _userManager.FindByEmailAsync(Admin.Email);

            try
            {
                await _userManager.DeleteAsync(user);
                await _adminRepo.DeleteAsync(Admin);
                return RedirectToAction(nameof(All));

            }
            catch
            {
                return View(admin);
            }
        }

       

    }
}

HRM_System/Controllers/RolesController.cs
using HRM_System.Data.Base;
using HRM_System.Data;
using HRM_System.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using HRM_System.Models.ViewModel;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Linq;
using System.Security.Claims;
using HRM_System.Constants;
using Constants;

namespace HRM_System.Controllers
{
    public class RolesController : Controller
    {
        private readonly IEntityRepository<Admin> _adminRepo;
        private readonly IEntityRepository<HRUser> _HRRepo;
        private readonly UserManager<HRUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly AppDbContext _context;

        public RolesController(IEntityRepository<Admin> adminRepo,
            IEntityRepository<HRUser> HRRepo,
            UserManager<HRUser> userManager,
            RoleManager<IdentityRole> roleManager, AppDbContext context)
        {
            _adminRepo = adminRepo;
            _HRRepo = HRRepo;
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        public IActionResult Create()
        {

            var allClaims = permissions.GenerateAllPermissions();
            var allPermissions = allClaims.Select(p => new CheckBoxViewModel { DisplayValue = p }).ToList();


            var viewModel = new RoleFormViewModel
            {
                RoleCalims = allPermissions
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _roleManager.RoleExistsAsync(model.Name.Trim()))
                {
                    ModelState.AddModelError("Name", "Role is exists!");
                    return View(model);
                }

                var role = new IdentityRole(model.Name.Trim());
                var identityResult = await _roleManager.CreateAsync(role);

                if (identityResult.Succeeded)
                {

                  //  var role = await _roleManager.FindByNameAsync(model.Name.Trim());


                    var selectedClaims = model.RoleCalims.Where(c => c.IsSelected).ToList();

                    foreach (var claim in selectedClaims)
                    {
                        await _roleManager.AddClaimAsync(role, new Claim("Permission", claim.DisplayValue));
                    }

                    return View("Index", await _roleManager.Roles.ToListAsync());
                }
                else
                {

                    foreach (var error in identityResult.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(model);
        }
        public async Task<IActionResult> ManagePermissions(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
                return NotFound();

            var roleClaims = _roleManager.GetClaimsAsync(role).Result.Select(c => c.Value).ToList();
            var allClaims = permissions.GenerateAllPermissions();
            var allPermissions = allClaims.Select(p => new CheckBoxViewModel { DisplayValue = p }).ToList();

            foreach (var permission in allPermissions)
            {
                if (roleClaims.Any(c => c == permission.DisplayValue))
                    permission.IsSelected = true;
            }

            var viewModel = new PermissionsFormViewModel
            {
                RoleId = roleId,
                RoleName = role.Name,
                RoleCalims = allPermissions
            };

            return View(viewModel);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> ManagePermissions(PermissionsFormViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);

            if (role == null)
                return NotFound();

            var roleClaims = await _roleManager.GetClaimsAsync(role);

            foreach (var claim in roleClaims)
                await _roleManager.RemoveClaimAsync(role, claim);

            var selectedClaims = model.RoleCalims.Where(c => c.IsSelected).ToList();

            foreach (var claim in selectedClaims)
                await _roleManager.AddClaimAsync(role, new Claim("Permission", claim.DisplayValue));

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Details(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
                return NotFound();

            var roleClaims = _roleManager.GetClaimsAsync(role).Result.Select(c => c.Value).ToList();
            var allClaims = permissions.GenerateAllPermissions();
            var allPermissions = allClaims.Select(p => new CheckBoxViewModel { DisplayValue = p }).ToList();

            foreach (var permission in allPermissions)
            {
                if (roleClaims.Any(c => c == permission.DisplayValue))
                    permission.IsSelected = true;
            }

            var viewModel = new PermissionsFormViewModel
            {
                RoleId = roleId,
                RoleName = role.Name,
                RoleCalims = allPermissions
            };

            return View(viewModel);
        }
        public Task<IActionResult> Delete(string roleId)
        {
            return ManagePermissions(roleId);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] string roleId, PermissionsFormViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);

            if (role == null)
                return NotFound();

            try
            {
                var roleClaims = await _roleManager.GetClaimsAsync(role);

                foreach (var claim in roleClaims)
                    await _roleManager.RemoveClaimAsync(role, claim);

                var deleterole = await _roleManager.DeleteAsync(role);
                if (deleterole.Succeeded)
                {
                    return RedirectToAction(nameof(Index));

                }
                return View(model);

            }
            catch
            {
                return View(model);
            }
        }
    }
}

HRM_System/Controllers/SalaryDataController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using HRM_System.Data.Base;
using HRM_System.Models;
using HRM_System.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HRM_System.Controllers
{
    public class SalaryDataController : Controller
    {
        private readonly IEntityRepository<SalaryData> _salaryRepo;
        private readonly IEntityRepository<Employee> _empRepo;

        public SalaryDataController(IEntityRepository<SalaryData> salaryRepo,
            IEntityRepository<Employee> empRepo)
        {
            _salaryRepo = salaryRepo;
            _empRepo = empRepo;
        }

        //public IActionResult GetSalary()
        //{
        //    return View();
        //}

        //[HttpPost]
        public async Task<IActionResult> GetSalary(string Name, Months Month, int Year)
        {

            var employee = (await _empRepo.GetAllAsync(e => e.Name.Contains(Name))).FirstOrDefault();
            if (employee == null)
            {
                return View();
            }
            else
            {
                return await Details(Name, Month, Year);
            }

        }

        
        public async Task<IActionResult> Details(string Name, Months Month, int Year)
        {
            var employee = (await _empRepo.GetAllAsync(e => e.Name.Contains(Name))).Include(e=>e.WorkData).FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            int recorddays = _salaryRepo.Getrecorddays(employee.Id, Month.ToString(), Year);
            int daysofabsence = _salaryRepo.GetDaysofAbsence(employee.Id, Month, Year);
            int additional_hours = _salaryRepo.GetExtraTotalHoursPerMonth(employee.Id, Month, Year);
            int discount_per_hour = _salaryRepo.GetTotalDiscountHoursPerMonth(employee.Id, Month, Year);
            int extratotal = _salaryRepo.GetExtraTotalPerMonth(employee.Id, Month, Year);
            int totaldiscount = _salaryRepo.GetTotalDiscountPerMonth(employee.Id, Month, Year);
            int netsalary = await _salaryRepo.GetNetSalary(employee.Id, Month, Year);

            var salary = new SalaryDataViewModel()
            {
                EmployeeName = Name,
                Department = employee.Deparment,
                Salary = employee.WorkData.Salary,
                RecordDays =recorddays,
                Daysofabsence = daysofabsence,
                Additional_hours =additional_hours,
                Discount_per_hour =discount_per_hour,
                ExtraTotal =extratotal,
                TotalDiscount =totaldiscount,
                NetSalary = netsalary,
            };

            return View(salary);
        }

        //public ActionResult PrintSalary(int employeeId)
        //{
        //    var employee = _salaryRepo.GetByIdAsync(employeeId);

        //    return View("PrintSalary", employee);
        //}
        //public IActionResult Edit(int? id)
        //{
        //    return View();
        //}

        //[HttpPost]
        //public async Task<IActionResult> Edit([FromRoute] int? id, SalaryData salaryData)
        //{
        //    if (id != salaryData.EmployeeId)
        //        return BadRequest();
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            await _salaryRepo.UpdateAsync(salaryData);
        //            return RedirectToAction(nameof(HomeController.Index));
        //        }
        //        catch
        //        {
        //            return View(salaryData);
        //        }
        //    }
        //    return View(salaryData);
        //}


    }
}

HRM_System/Views/Shared/SignInlayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		@RenderBody() 
		<!-- copyright -->
		@*<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>*@
		<!-- //copyright -->
		@*<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>*@
	</div>
	<!-- //main -->
</body>
</html>

HRM_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRM_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRM_System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
         @*               @if (User.IsInRole(Roles.HRAdmin.ToString()))
                        {*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> مجموعة المستخدمين
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Roles" asp-action="Create"><i class="bi bi-camera-reels"></i>اضافة مجموعة جديدة </a>
                                <a class="dropdown-item" asp-controller="Roles" asp-action="Index"><i class="bi bi-camera-reels"></i>مجموعات الصلاحيات</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> مستخدمين النظام
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Admins" asp-action="CreateAdmin"><i class="bi bi-camera-reels"></i> Add New Admin</a>
                                <a class="dropdown-item" asp-controller="Admins" asp-action="All"><i class="bi bi-headset"></i> Get All Admins</a>
                                
                            </div>
                        </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> الاجازات الرسمية
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Officialleavesettings" asp-action="Index"><i class="bi bi-headset"></i>الاجازات الرسمية</a>

                                </div>
                            </li>
                       @* }*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> الموظفين
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Employees" asp-action="Create"><i class="bi bi-camera-reels"></i> Add New Employee</a>
                                <a class="dropdown-item" asp-controller="Employees" asp-action="All"><i class="bi bi-headset"></i> Get All Employees</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> اعدادات عامة
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="GeneralSettings" asp-action="Create"><i class="bi bi-camera-reels"></i>Add General Settings</a>
                                <a class="dropdown-item" asp-controller="GeneralSettings" asp-action="All"><i class="bi bi-headset"></i> View General Settings</a>

                            </div>
                        </li>
                       
                        <li class="nav-item ">
                            
                            <a class="nav-link text-dark" asp-controller="AttendanceAndDepartureofEmployees" asp-action="GetAll">تقرير حضور وانصراف الموظفين</a>
                        </li>
                        <li class="nav-item dropdown">
                            
                            <a class="nav-link text-dark" asp-controller="SalaryData" asp-action="GetSalary">رواتب الموظفين</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HRM_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("scriptSection", required: false)
</body>
</html>